/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */
val outputJarBaseName = "avaj-runner"
val version = "1.0-SNAPSHOT"

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass.set("avaj.launcher.AvajLauncher")
}

tasks.jar {
    archiveBaseName.set(outputJarBaseName)    // nom principal du jar, ex: avaj-runner
    archiveVersion.set(version)              // version du jar, ex: 1.0-SNAPSHOT
    // archiveClassifier.set("")               // décommenter si vous voulez enlever le classifier
    manifest {
        attributes["Main-Class"] = "avaj.launcher.AvajLauncher"
    }
}

// Tâche personnalisée pour exécuter l'application avec un fichier de scénario
tasks.register<JavaExec>("runScenario") {
    group = "application"
    description = "Exécute l'application avec un fichier de scénario spécifié"
    
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set("avaj.launcher.AvajLauncher")
    workingDir = project.rootDir  // Définit le répertoire de travail sur la racine du projet
    
    // Le fichier de scénario doit être passé via la propriété 'scenarioFile'
    // Exemple: ./gradlew runScenario -PscenarioFile=scenario.txt
    args(findProperty("scenarioFile") ?: "scenario.txt")
}

// Tâche temporaire pour afficher le classpath (utilisée par le Makefile)
tasks.register("printClasspath") {
    doLast {
        println(sourceSets.main.get().runtimeClasspath.asPath)
    }
}